language: python

python:
  - 3.6

services:
  - docker

before_install:
  - pip install codecov
  - pip install nose

install:
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt

script:
  - nosetests -v --with-coverage --cover-package=gitlabbuildvariables --cover-inclusive

after_success:
  - codecov
