language: python

python:
  - 3.6

services:
  - docker

before_install:
  - pip install codecov
  - pip install coverage

install:
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt

script:
  - PYTHONPATH=. coverage run -m unittest discover -v -s .
  - coverage run setup.py install
  - coverage combine -a
  - coverage report

after_success:
  - codecov
