language: python

python:
  - 3.6

services:
  - docker

before_install:
  - pip install codecov

install:
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt

script:
  - PYTHONPATH=. python -m unittest discover -v -s .

after_success:
  - codecov
